Repository krferrell/framer-motion, pull requests merged in 2022-05, with the labels that each got.

#17 Create Hovers Page
  src/App.js
  src/components/navigation/Nav.js
  src/pages/hover/Hovers.js
  src/pages/hover/hoverVariants.js
  src/pages/index.js
Labels: enhancement

#21 Created a `useAnimation` Hook Presentation
  package-lock.json
  package.json
  src/App.js
  src/use-animation/DynamicControls/Dynamic.jsx
  src/use-animation/DynamicControls/NonDynamic.jsx
  src/use-animation/DynamicControls/index.js
  src/use-animation/DynamicControls/styles.js
  src/use-animation/IntersectionObserver/Intersection.jsx
  src/use-animation/IntersectionObserver/NoIntersection.jsx
  src/use-animation/IntersectionObserver/index.js
  src/use-animation/IntersectionObserver/styles.js
  src/use-animation/SimpleControls/index.jsx
  src/use-animation/SimpleControls/reactoad.png
  src/use-animation/SimpleControls/styles.js
Labels: enhancement

#24 refactor(file-system): restructure file system
  package-lock.json
  package.json
  src/App.js
  src/FramerDemo/Animations/Drag/Drag.js
  src/FramerDemo/Animations/Hover/Hover.js
  src/FramerDemo/Animations/Modal/Modal.js
  src/FramerDemo/Animations/OnLoad/OnLoad.js
  src/FramerDemo/Animations/SVG/SVG.js
  src/FramerDemo/Animations/Staggered/Staggered.js
  src/FramerDemo/Animations/Toggle/Toggle.js
  src/FramerDemo/Animations/index.js
  src/FramerDemo/FramerDemo.js
  src/FramerDemo/styles.js
  src/PureCss/PureCss.js
  src/PureCss/styles.css
  src/components/customComponent/CustomComp.js
  src/components/index.js
  src/components/nameTag/NameTag.js
  src/components/nameTag/nameTagVatiant.js
  src/components/navigation/Nav.js
  src/index.css
  src/pages/home/Home.js
  src/pages/hover/Hovers.js
  src/pages/index.js
  src/pages/syledCompEx/StyledCompEx.js
  src/use-animation/DynamicControls/Dynamic.jsx
  src/use-animation/DynamicControls/NonDynamic.jsx
  src/use-animation/DynamicControls/index.js
  src/use-animation/DynamicControls/styles.js
  src/use-animation/IntersectionObserver/Intersection.jsx
  src/use-animation/IntersectionObserver/NoIntersection.jsx
  src/use-animation/IntersectionObserver/index.js
  src/use-animation/IntersectionObserver/styles.js
  src/use-animation/SimpleControls/index.jsx
  src/use-animation/SimpleControls/reactoad.png
  src/use-animation/SimpleControls/styles.js
  src/utils/data.js
Labels: enhancement

#32 Created Staggered Component
  src/FramerDemo/Animations/Staggered/Staggered.js
  src/FramerDemo/Animations/Staggered/index.js
  src/FramerDemo/Animations/Staggered/staggeredCodeblockString.js
  src/FramerDemo/Animations/Staggered/styles.js
  src/FramerDemo/Animations/Staggered/variants.js
  src/Modal/Modal.js
  src/components/navigation/Nav.js
  src/index.js
Labels: enhancement

#52 Setup Animation Focus
  src/FramerDemo/Animations/Drag/Drag.js
  src/FramerDemo/Animations/Hover/Hover.js
  src/FramerDemo/Animations/Modal/Modal.js
  src/FramerDemo/Animations/SVG/SVG.js
  src/FramerDemo/Animations/Staggered/styles.js
  src/FramerDemo/Components/AnimationGrid/AnimationGrid.jsx
  src/FramerDemo/Components/AnimationGrid/Cards/Cards.js
  src/FramerDemo/Components/AnimationGrid/Cards/styles.js
  src/FramerDemo/Components/Sidebar/Sidebar.jsx
  src/FramerDemo/FramerDemo.js
Labels: enhancement

#56 Updated the README
  .github/CODEOWNERS
  README.md
Labels: documentation, enhancement

#62 Updated the README
  README.md
Labels: documentation
